# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import accounts_pb2 as accounts__pb2
import grpc

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in accounts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/workoutapp.accounts.AccountsService/GetProfile',
                request_serializer=accounts__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=accounts__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/workoutapp.accounts.AccountsService/UpdateProfile',
                request_serializer=accounts__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=accounts__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.UploadAvatar = channel.unary_unary(
                '/workoutapp.accounts.AccountsService/UploadAvatar',
                request_serializer=accounts__pb2.UploadAvatarRequest.SerializeToString,
                response_deserializer=accounts__pb2.UploadAvatarResponse.FromString,
                _registered_method=True)


class AccountsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=accounts__pb2.GetProfileRequest.FromString,
                    response_serializer=accounts__pb2.GetProfileResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=accounts__pb2.UpdateProfileRequest.FromString,
                    response_serializer=accounts__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'UploadAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadAvatar,
                    request_deserializer=accounts__pb2.UploadAvatarRequest.FromString,
                    response_serializer=accounts__pb2.UploadAvatarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workoutapp.accounts.AccountsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workoutapp.accounts.AccountsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.accounts.AccountsService/GetProfile',
            accounts__pb2.GetProfileRequest.SerializeToString,
            accounts__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.accounts.AccountsService/UpdateProfile',
            accounts__pb2.UpdateProfileRequest.SerializeToString,
            accounts__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.accounts.AccountsService/UploadAvatar',
            accounts__pb2.UploadAvatarRequest.SerializeToString,
            accounts__pb2.UploadAvatarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
