"""Initial schema

Revision ID: 8b2dc5470e8d
Revises: 
Create Date: 2026-07-02 12:08:45.211067
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8b2dc5470e8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('macro_suggestion', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_workout_id'), 'workout_sessions', ['workout_id'], unique=False)
    op.create_table('applied_mesocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applied_plan_id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applied_plan_id'], ['applied_calendar_plans.id'], ),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_mesocycles_id'), 'applied_mesocycles', ['id'], unique=False)
    op.create_table('applied_plan_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applied_plan_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('nutrition_plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['applied_plan_id'], ['applied_calendar_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_plan_workouts_id'), 'applied_plan_workouts', ['id'], unique=False)
    op.create_table('microcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('normalization_value', sa.Float(), nullable=True),
    sa.Column('normalization_unit', sa.String(length=16), nullable=True),
    sa.Column('normalization_rules', sa.JSON(), nullable=True),
    sa.Column('days_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcycles_id'), 'microcycles', ['id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('effort', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('working_weight', sa.Float(), nullable=True),
    sa.Column('set_type', sa.String(length=32), nullable=True),
    sa.Column('subsets', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_id'), 'workout_sets', ['id'], unique=False)
    op.create_table('applied_microcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applied_mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('microcycle_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applied_mesocycle_id'], ['applied_mesocycles.id'], ),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_microcycles_id'), 'applied_microcycles', ['id'], unique=False)
    op.create_table('plan_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microcycle_id', sa.Integer(), nullable=False),
    sa.Column('day_label', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('nutrition_plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_workouts_id'), 'plan_workouts', ['id'], unique=False)
    op.create_table('applied_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applied_microcycle_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applied_microcycle_id'], ['applied_microcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_workouts_id'), 'applied_workouts', ['id'], unique=False)
    op.create_table('plan_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_workout_id'], ['plan_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_exercises_id'), 'plan_exercises', ['id'], unique=False)
    op.create_table('plan_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=32), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('working_weight', sa.Float(), nullable=True),
    sa.Column('subsets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_exercise_id'], ['plan_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_sets_id'), 'plan_sets', ['id'], unique=False)
    op.create_table('workout_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_exercise_id', sa.Integer(), nullable=True),
    sa.Column('workout_set_id', sa.Integer(), nullable=False),
    sa.Column('planned_intensity', sa.Integer(), nullable=True),
    sa.Column('actual_intensity', sa.Float(), nullable=True),
    sa.Column('planned_effort', sa.Integer(), nullable=True),
    sa.Column('actual_effort', sa.Float(), nullable=True),
    sa.Column('planned_volume', sa.Integer(), nullable=True),
    sa.Column('actual_volume', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_exercise_id'], ['plan_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_progress_id'), 'workout_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_progress_id'), table_name='workout_progress')
    op.drop_table('workout_progress')
    op.drop_index(op.f('ix_plan_sets_id'), table_name='plan_sets')
    op.drop_table('plan_sets')
    op.drop_index(op.f('ix_plan_exercises_id'), table_name='plan_exercises')
    op.drop_table('plan_exercises')
    op.drop_index(op.f('ix_applied_workouts_id'), table_name='applied_workouts')
    op.drop_table('applied_workouts')
    op.drop_index(op.f('ix_plan_workouts_id'), table_name='plan_workouts')
    op.drop_table('plan_workouts')
    op.drop_index(op.f('ix_applied_microcycles_id'), table_name='applied_microcycles')
    op.drop_table('applied_microcycles')
    op.drop_index(op.f('ix_workout_sets_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_microcycles_id'), table_name='microcycles')
    op.drop_table('microcycles')
    op.drop_index(op.f('ix_applied_plan_workouts_id'), table_name='applied_plan_workouts')
    op.drop_table('applied_plan_workouts')
    op.drop_index(op.f('ix_applied_mesocycles_id'), table_name='applied_mesocycles')
    op.drop_table('applied_mesocycles')
    op.drop_index(op.f('ix_workout_sessions_workout_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
