"""user-max: update models

Revision ID: 6c124a36e8ca
Revises: 339bf2c24eaf
Create Date: 2025-11-23 13:21:25.759056
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c124a36e8ca"
down_revision = "339bf2c24eaf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
