"""add_exercise_name_to_user_max

Revision ID: e011d561b6c7
Revises: 7ded9e261229
Create Date: 2025-09-17 13:10:53.957298
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e011d561b6c7'
down_revision = '7ded9e261229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_maxes', sa.Column('exercise_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_maxes', 'exercise_name')
    # ### end Alembic commands ###
