"""add_app_id_and_context

Revision ID: d70fa1c82161
Revises: 002
Create Date: 2025-11-22 07:19:16.610328

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd70fa1c82161'
down_revision: str | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('app_id', sa.String(length=50), nullable=True))
    op.add_column('channels', sa.Column('context_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_channels_app_id'), 'channels', ['app_id'], unique=False)
    op.create_index(op.f('ix_channels_type'), 'channels', ['type'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.add_column('messages', sa.Column('app_id', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('context_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_messages_channel_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_id'), table_name='messages')
    op.create_index(op.f('ix_messages_app_id'), 'messages', ['app_id'], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_index(op.f('idx_outbox_created_at'), table_name='outbox_events')
    op.drop_index(op.f('idx_outbox_stream_name'), table_name='outbox_events')
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_stream_name'), 'outbox_events', ['stream_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_stream_name'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.create_index(op.f('idx_outbox_stream_name'), 'outbox_events', ['stream_name'], unique=False)
    op.create_index(op.f('idx_outbox_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_app_id'), table_name='messages')
    op.create_index(op.f('idx_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.drop_column('messages', 'context_resource')
    op.drop_column('messages', 'app_id')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_channels_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_app_id'), table_name='channels')
    op.drop_column('channels', 'context_resource')
    op.drop_column('channels', 'app_id')
    # ### end Alembic commands ###
