"""workouts: update models"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a83df4f79d7"
down_revision = "3120406ae26b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workouts_plan_workout_id", table_name="workouts")
    op.drop_index(
        "ix_workouts_unique_plan_order",
        table_name="workouts",
        postgresql_where="((applied_plan_id IS NOT NULL) AND (plan_order_index IS NOT NULL))",
    )
    op.drop_index("ix_workouts_workout_type", table_name="workouts")
    op.drop_column("workouts", "is_template")
    op.drop_column("workouts", "plan_workout_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("plan_workout_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("workouts", sa.Column("is_template", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index("ix_workouts_workout_type", "workouts", ["workout_type"], unique=False)
    op.create_index(
        "ix_workouts_unique_plan_order",
        "workouts",
        ["user_id", "applied_plan_id", "plan_order_index"],
        unique=True,
        postgresql_where="((applied_plan_id IS NOT NULL) AND (plan_order_index IS NOT NULL))",
    )
    op.create_index("ix_workouts_plan_workout_id", "workouts", ["plan_workout_id"], unique=False)
    # ### end Alembic commands ###
