"""workouts: update models"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3120406ae26b'
down_revision = '2025_10_28_macro_suggestion'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workout_exercises_id'), 'workout_exercises', ['id'], unique=False)
    op.alter_column('workout_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workout_sessions', 'progress',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.add_column('workout_sets', sa.Column('set_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_workout_sets_id'), 'workout_sets', ['id'], unique=False)
    op.alter_column('workouts', 'workout_type',
               existing_type=postgresql.ENUM('manual', 'generated', name='workouttypeenum'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('plan_workout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workouts', sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_workouts_workout_type', 'workouts', ['workout_type'], unique=False)
    op.create_index('ix_workouts_unique_plan_order', 'workouts', ['user_id', 'applied_plan_id', 'plan_order_index'], unique=True, postgresql_where='((applied_plan_id IS NOT NULL) AND (plan_order_index IS NOT NULL))')
    op.create_index('ix_workouts_plan_workout_id', 'workouts', ['plan_workout_id'], unique=False)
    op.alter_column('workouts', 'workout_type',
               existing_type=postgresql.ENUM('manual', 'generated', name='workouttypeenum'),
               server_default=sa.text("'manual'::workouttypeenum"),
               existing_nullable=False)
    op.alter_column('workout_sessions', 'progress',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('workout_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
