"""workouts: update models"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f98d65839be"
down_revision = "b99e9d1322ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
