"""workouts: update models"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba3ad8ceacda"
down_revision = "bafcc03e7c8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
