"""Initial migration"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6525343955a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS workouttypeenum")
    op.execute("CREATE TYPE workouttypeenum AS ENUM ('manual', 'generated')")
    workout_type = sa.Enum("manual", "generated", name="workouttypeenum", create_type=False)

    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("applied_plan_id", sa.Integer(), nullable=True),
        sa.Column("plan_order_index", sa.Integer(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("rpe_session", sa.Float(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("readiness_score", sa.Integer(), nullable=True),
        sa.Column("workout_type", sa.String(length=64), nullable=False, server_default="manual"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_name"), "workouts", ["name"], unique=False)

    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "workout_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=True),
        sa.Column("effort", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("working_weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["exercise_id"], ["workout_exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False, server_default="active"),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("progress", sa.JSON(), nullable=False, server_default="{}"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_sessions_workout_id"), "workout_sessions", ["workout_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_sessions_workout_id"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_table("workout_sets")
    op.drop_table("workout_exercises")
    op.drop_index(op.f("ix_workouts_name"), table_name="workouts")
    op.drop_table("workouts")
    op.execute("DROP TYPE IF EXISTS workouttypeenum")
    # ### end Alembic commands ###
