# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import workouts_pb2 as workouts__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workouts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkoutServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/CreateWorkout',
                request_serializer=workouts__pb2.CreateWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.CreateWorkoutResponse.FromString,
                _registered_method=True)
        self.GetWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/GetWorkout',
                request_serializer=workouts__pb2.GetWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.GetWorkoutResponse.FromString,
                _registered_method=True)
        self.GetWorkoutWithDetails = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/GetWorkoutWithDetails',
                request_serializer=workouts__pb2.GetWorkoutWithDetailsRequest.SerializeToString,
                response_deserializer=workouts__pb2.GetWorkoutWithDetailsResponse.FromString,
                _registered_method=True)
        self.UpdateWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/UpdateWorkout',
                request_serializer=workouts__pb2.UpdateWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.UpdateWorkoutResponse.FromString,
                _registered_method=True)
        self.ListWorkouts = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/ListWorkouts',
                request_serializer=workouts__pb2.ListWorkoutsRequest.SerializeToString,
                response_deserializer=workouts__pb2.ListWorkoutsResponse.FromString,
                _registered_method=True)
        self.GetNextWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/GetNextWorkout',
                request_serializer=workouts__pb2.GetNextWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.GetNextWorkoutResponse.FromString,
                _registered_method=True)
        self.StartWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/StartWorkout',
                request_serializer=workouts__pb2.StartWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.StartWorkoutResponse.FromString,
                _registered_method=True)
        self.FinishWorkout = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/FinishWorkout',
                request_serializer=workouts__pb2.FinishWorkoutRequest.SerializeToString,
                response_deserializer=workouts__pb2.FinishWorkoutResponse.FromString,
                _registered_method=True)
        self.ReplaceExercise = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/ReplaceExercise',
                request_serializer=workouts__pb2.ReplaceExerciseRequest.SerializeToString,
                response_deserializer=workouts__pb2.ReplaceExerciseResponse.FromString,
                _registered_method=True)
        self.GetActiveSession = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/GetActiveSession',
                request_serializer=workouts__pb2.GetActiveSessionRequest.SerializeToString,
                response_deserializer=workouts__pb2.GetActiveSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionHistory = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/GetSessionHistory',
                request_serializer=workouts__pb2.GetSessionHistoryRequest.SerializeToString,
                response_deserializer=workouts__pb2.GetSessionHistoryResponse.FromString,
                _registered_method=True)
        self.ListAllSessions = channel.unary_unary(
                '/workoutapp.workouts.WorkoutService/ListAllSessions',
                request_serializer=workouts__pb2.ListAllSessionsRequest.SerializeToString,
                response_deserializer=workouts__pb2.ListAllSessionsResponse.FromString,
                _registered_method=True)


class WorkoutServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkoutWithDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkouts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceExercise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkout,
                    request_deserializer=workouts__pb2.CreateWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.CreateWorkoutResponse.SerializeToString,
            ),
            'GetWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkout,
                    request_deserializer=workouts__pb2.GetWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.GetWorkoutResponse.SerializeToString,
            ),
            'GetWorkoutWithDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkoutWithDetails,
                    request_deserializer=workouts__pb2.GetWorkoutWithDetailsRequest.FromString,
                    response_serializer=workouts__pb2.GetWorkoutWithDetailsResponse.SerializeToString,
            ),
            'UpdateWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkout,
                    request_deserializer=workouts__pb2.UpdateWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.UpdateWorkoutResponse.SerializeToString,
            ),
            'ListWorkouts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkouts,
                    request_deserializer=workouts__pb2.ListWorkoutsRequest.FromString,
                    response_serializer=workouts__pb2.ListWorkoutsResponse.SerializeToString,
            ),
            'GetNextWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextWorkout,
                    request_deserializer=workouts__pb2.GetNextWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.GetNextWorkoutResponse.SerializeToString,
            ),
            'StartWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkout,
                    request_deserializer=workouts__pb2.StartWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.StartWorkoutResponse.SerializeToString,
            ),
            'FinishWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishWorkout,
                    request_deserializer=workouts__pb2.FinishWorkoutRequest.FromString,
                    response_serializer=workouts__pb2.FinishWorkoutResponse.SerializeToString,
            ),
            'ReplaceExercise': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceExercise,
                    request_deserializer=workouts__pb2.ReplaceExerciseRequest.FromString,
                    response_serializer=workouts__pb2.ReplaceExerciseResponse.SerializeToString,
            ),
            'GetActiveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveSession,
                    request_deserializer=workouts__pb2.GetActiveSessionRequest.FromString,
                    response_serializer=workouts__pb2.GetActiveSessionResponse.SerializeToString,
            ),
            'GetSessionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionHistory,
                    request_deserializer=workouts__pb2.GetSessionHistoryRequest.FromString,
                    response_serializer=workouts__pb2.GetSessionHistoryResponse.SerializeToString,
            ),
            'ListAllSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllSessions,
                    request_deserializer=workouts__pb2.ListAllSessionsRequest.FromString,
                    response_serializer=workouts__pb2.ListAllSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workoutapp.workouts.WorkoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workoutapp.workouts.WorkoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkoutService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/CreateWorkout',
            workouts__pb2.CreateWorkoutRequest.SerializeToString,
            workouts__pb2.CreateWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/GetWorkout',
            workouts__pb2.GetWorkoutRequest.SerializeToString,
            workouts__pb2.GetWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkoutWithDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/GetWorkoutWithDetails',
            workouts__pb2.GetWorkoutWithDetailsRequest.SerializeToString,
            workouts__pb2.GetWorkoutWithDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/UpdateWorkout',
            workouts__pb2.UpdateWorkoutRequest.SerializeToString,
            workouts__pb2.UpdateWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkouts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/ListWorkouts',
            workouts__pb2.ListWorkoutsRequest.SerializeToString,
            workouts__pb2.ListWorkoutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/GetNextWorkout',
            workouts__pb2.GetNextWorkoutRequest.SerializeToString,
            workouts__pb2.GetNextWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/StartWorkout',
            workouts__pb2.StartWorkoutRequest.SerializeToString,
            workouts__pb2.StartWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/FinishWorkout',
            workouts__pb2.FinishWorkoutRequest.SerializeToString,
            workouts__pb2.FinishWorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceExercise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/ReplaceExercise',
            workouts__pb2.ReplaceExerciseRequest.SerializeToString,
            workouts__pb2.ReplaceExerciseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/GetActiveSession',
            workouts__pb2.GetActiveSessionRequest.SerializeToString,
            workouts__pb2.GetActiveSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/GetSessionHistory',
            workouts__pb2.GetSessionHistoryRequest.SerializeToString,
            workouts__pb2.GetSessionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.workouts.WorkoutService/ListAllSessions',
            workouts__pb2.ListAllSessionsRequest.SerializeToString,
            workouts__pb2.ListAllSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
