"""Add exercise and workout templates

Revision ID: c23459d0b784
Revises: 073a55c4db5e
Create Date: 2025-05-28 10:37:01.604774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23459d0b784'
down_revision: Union[str, None] = '073a55c4db5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type if it doesn't exist
    op.execute("CREATE TYPE userrole AS ENUM ('ATHLETE', 'TRAINER', 'ADMIN')")
    
    # Then alter the column with explicit cast
    op.execute('''
        ALTER TABLE users 
        ALTER COLUMN role 
        TYPE userrole USING role::userrole
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First convert the enum to text
    op.execute('''
        ALTER TABLE users 
        ALTER COLUMN role 
        TYPE VARCHAR USING role::text
    ''')
    
    # Then drop the enum type
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
