# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accounts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ounts.proto\x12\x13workoutapp.accounts\x1a\x0c\x63ommon.proto\"\xc2\x01\n\x07Profile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tphoto_url\x18\x04 \x01(\t\x12\x42\n\x0bpreferences\x18\x05 \x03(\x0b\x32-.workoutapp.accounts.Profile.PreferencesEntry\x1a\x32\n\x10PreferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"I\n\x11GetProfileRequest\x12\x34\n\x0cuser_context\x18\x01 \x01(\x0b\x32\x1e.workoutapp.common.UserContext\"C\n\x12GetProfileResponse\x12-\n\x07profile\x18\x01 \x01(\x0b\x32\x1c.workoutapp.accounts.Profile\"{\n\x14UpdateProfileRequest\x12-\n\x07profile\x18\x01 \x01(\x0b\x32\x1c.workoutapp.accounts.Profile\x12\x34\n\x0cuser_context\x18\x02 \x01(\x0b\x32\x1e.workoutapp.common.UserContext\"F\n\x15UpdateProfileResponse\x12-\n\x07profile\x18\x01 \x01(\x0b\x32\x1c.workoutapp.accounts.Profile\"u\n\x13UploadAvatarRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x34\n\x0cuser_context\x18\x03 \x01(\x0b\x32\x1e.workoutapp.common.UserContext\")\n\x14UploadAvatarResponse\x12\x11\n\tphoto_url\x18\x01 \x01(\t2\xbd\x02\n\x0f\x41\x63\x63ountsService\x12]\n\nGetProfile\x12&.workoutapp.accounts.GetProfileRequest\x1a\'.workoutapp.accounts.GetProfileResponse\x12\x66\n\rUpdateProfile\x12).workoutapp.accounts.UpdateProfileRequest\x1a*.workoutapp.accounts.UpdateProfileResponse\x12\x63\n\x0cUploadAvatar\x12(.workoutapp.accounts.UploadAvatarRequest\x1a).workoutapp.accounts.UploadAvatarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE_PREFERENCESENTRY']._loaded_options = None
  _globals['_PROFILE_PREFERENCESENTRY']._serialized_options = b'8\001'
  _globals['_PROFILE']._serialized_start=54
  _globals['_PROFILE']._serialized_end=248
  _globals['_PROFILE_PREFERENCESENTRY']._serialized_start=198
  _globals['_PROFILE_PREFERENCESENTRY']._serialized_end=248
  _globals['_GETPROFILEREQUEST']._serialized_start=250
  _globals['_GETPROFILEREQUEST']._serialized_end=323
  _globals['_GETPROFILERESPONSE']._serialized_start=325
  _globals['_GETPROFILERESPONSE']._serialized_end=392
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=394
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=517
  _globals['_UPDATEPROFILERESPONSE']._serialized_start=519
  _globals['_UPDATEPROFILERESPONSE']._serialized_end=589
  _globals['_UPLOADAVATARREQUEST']._serialized_start=591
  _globals['_UPLOADAVATARREQUEST']._serialized_end=708
  _globals['_UPLOADAVATARRESPONSE']._serialized_start=710
  _globals['_UPLOADAVATARRESPONSE']._serialized_end=751
  _globals['_ACCOUNTSSERVICE']._serialized_start=754
  _globals['_ACCOUNTSSERVICE']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
