# Generated by Django 4.2.16 on 2025-02-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
    ]
