# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import exercises_pb2 as exercises__pb2
import grpc

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exercises_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExercisesServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExercise = channel.unary_unary(
                '/workoutapp.exercises.ExercisesService/GetExercise',
                request_serializer=exercises__pb2.GetExerciseRequest.SerializeToString,
                response_deserializer=exercises__pb2.GetExerciseResponse.FromString,
                _registered_method=True)
        self.GetExerciseDefinitions = channel.unary_unary(
                '/workoutapp.exercises.ExercisesService/GetExerciseDefinitions',
                request_serializer=exercises__pb2.GetExerciseDefinitionsRequest.SerializeToString,
                response_deserializer=exercises__pb2.GetExerciseDefinitionsResponse.FromString,
                _registered_method=True)
        self.CreateExerciseInstances = channel.unary_unary(
                '/workoutapp.exercises.ExercisesService/CreateExerciseInstances',
                request_serializer=exercises__pb2.CreateExerciseInstancesRequest.SerializeToString,
                response_deserializer=exercises__pb2.CreateExerciseInstancesResponse.FromString,
                _registered_method=True)
        self.GetExerciseInstances = channel.unary_unary(
                '/workoutapp.exercises.ExercisesService/GetExerciseInstances',
                request_serializer=exercises__pb2.GetExerciseInstancesRequest.SerializeToString,
                response_deserializer=exercises__pb2.GetExerciseInstancesResponse.FromString,
                _registered_method=True)


class ExercisesServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetExercise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExerciseDefinitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExerciseInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExerciseInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExercisesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExercise': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExercise,
                    request_deserializer=exercises__pb2.GetExerciseRequest.FromString,
                    response_serializer=exercises__pb2.GetExerciseResponse.SerializeToString,
            ),
            'GetExerciseDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExerciseDefinitions,
                    request_deserializer=exercises__pb2.GetExerciseDefinitionsRequest.FromString,
                    response_serializer=exercises__pb2.GetExerciseDefinitionsResponse.SerializeToString,
            ),
            'CreateExerciseInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExerciseInstances,
                    request_deserializer=exercises__pb2.CreateExerciseInstancesRequest.FromString,
                    response_serializer=exercises__pb2.CreateExerciseInstancesResponse.SerializeToString,
            ),
            'GetExerciseInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExerciseInstances,
                    request_deserializer=exercises__pb2.GetExerciseInstancesRequest.FromString,
                    response_serializer=exercises__pb2.GetExerciseInstancesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workoutapp.exercises.ExercisesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workoutapp.exercises.ExercisesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExercisesService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExercise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.exercises.ExercisesService/GetExercise',
            exercises__pb2.GetExerciseRequest.SerializeToString,
            exercises__pb2.GetExerciseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExerciseDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.exercises.ExercisesService/GetExerciseDefinitions',
            exercises__pb2.GetExerciseDefinitionsRequest.SerializeToString,
            exercises__pb2.GetExerciseDefinitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExerciseInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.exercises.ExercisesService/CreateExerciseInstances',
            exercises__pb2.CreateExerciseInstancesRequest.SerializeToString,
            exercises__pb2.CreateExerciseInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExerciseInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workoutapp.exercises.ExercisesService/GetExerciseInstances',
            exercises__pb2.GetExerciseInstancesRequest.SerializeToString,
            exercises__pb2.GetExerciseInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
