"""add_nutrition_plan_column

Revision ID: 26d1a3bd8193
Revises: 878e898d470a
Create Date: 2026-04-17 15:17:41.600171
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26d1a3bd8193'
down_revision = '878e898d470a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index('ix_applied_calendar_plans_calendar_plan_id', table_name='applied_calendar_plans')
    op.drop_index('ux_applied_calendar_plans_active_user', table_name='applied_calendar_plans', postgresql_where='is_active')
    op.drop_index('ix_applied_mesocycles_applied_plan_id', table_name='applied_mesocycles')
    op.drop_index('ix_applied_microcycles_applied_mesocycle_id', table_name='applied_microcycles')
    op.drop_index('ix_applied_microcycles_microcycle_id', table_name='applied_microcycles')
    op.add_column('applied_plan_workouts', sa.Column('nutrition_plan', sa.JSON(), nullable=True))
    op.drop_index('ix_applied_workouts_applied_microcycle_id', table_name='applied_workouts')
    op.add_column('calendar_plans', sa.Column('nutrition_plan', sa.JSON(), nullable=True))
    op.alter_column('calendar_plans', 'root_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_mesocycles_calendar_plan_id', table_name='mesocycles')
    op.drop_index('ix_microcycles_mesocycle_id', table_name='microcycles')
    op.drop_index('ix_plan_adopters_adopter_user_id', table_name='plan_adopters')
    op.drop_index('ix_plan_adopters_root_plan_id', table_name='plan_adopters')
    op.drop_index('ix_plan_exercises_plan_workout_id', table_name='plan_exercises')
    op.drop_index('ix_plan_sets_plan_exercise_id', table_name='plan_sets')
    op.add_column('plan_workouts', sa.Column('nutrition_plan', sa.JSON(), nullable=True))
    op.drop_index('ix_plan_workouts_microcycle_id', table_name='plan_workouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_plan_workouts_microcycle_id', 'plan_workouts', ['microcycle_id'], unique=False)
    op.drop_column('plan_workouts', 'nutrition_plan')
    op.create_index('ix_plan_sets_plan_exercise_id', 'plan_sets', ['plan_exercise_id'], unique=False)
    op.create_index('ix_plan_exercises_plan_workout_id', 'plan_exercises', ['plan_workout_id'], unique=False)
    op.create_index('ix_plan_adopters_root_plan_id', 'plan_adopters', ['root_plan_id'], unique=False)
    op.create_index('ix_plan_adopters_adopter_user_id', 'plan_adopters', ['adopter_user_id'], unique=False)
    op.create_index('ix_microcycles_mesocycle_id', 'microcycles', ['mesocycle_id'], unique=False)
    op.create_index('ix_mesocycles_calendar_plan_id', 'mesocycles', ['calendar_plan_id'], unique=False)
    op.alter_column('calendar_plans', 'root_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('calendar_plans', 'nutrition_plan')
    op.create_index('ix_applied_workouts_applied_microcycle_id', 'applied_workouts', ['applied_microcycle_id'], unique=False)
    op.drop_column('applied_plan_workouts', 'nutrition_plan')
    op.create_index('ix_applied_microcycles_microcycle_id', 'applied_microcycles', ['microcycle_id'], unique=False)
    op.create_index('ix_applied_microcycles_applied_mesocycle_id', 'applied_microcycles', ['applied_mesocycle_id'], unique=False)
    op.create_index('ix_applied_mesocycles_applied_plan_id', 'applied_mesocycles', ['applied_plan_id'], unique=False)
    op.create_index('ux_applied_calendar_plans_active_user', 'applied_calendar_plans', ['user_id'], unique=True, postgresql_where='is_active')
    op.create_index('ix_applied_calendar_plans_calendar_plan_id', 'applied_calendar_plans', ['calendar_plan_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###
