"""Add user_id to plan models

Revision ID: 2967f6781457
Revises: 0004_drop_user_max_exercise_fk
Create Date: 2025-08-28 23:56:04.128742
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2967f6781457"
down_revision = "0004_drop_user_max_exercise_fk"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "applied_calendar_plan_user_maxes",
        "user_maxes",
        ["user_max_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "applied_calendar_plans", sa.Column("user_id", sa.String(), nullable=True)
    )
    op.execute(
        "UPDATE applied_calendar_plans SET user_id = 'admin_placeholder' WHERE user_id IS NULL"
    )
    op.alter_column(
        "applied_calendar_plans", "user_id", existing_type=sa.String(), nullable=False
    )
    op.alter_column(
        "applied_calendar_plans",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        op.f("ix_applied_calendar_plans_id"),
        "applied_calendar_plans",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applied_calendar_plans_user_id"),
        "applied_calendar_plans",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "calendar_plan_instances", sa.Column("user_id", sa.String(), nullable=True)
    )
    op.execute(
        "UPDATE calendar_plan_instances SET user_id = 'admin_placeholder' WHERE user_id IS NULL"
    )
    op.alter_column(
        "calendar_plan_instances", "user_id", existing_type=sa.String(), nullable=False
    )
    op.alter_column(
        "calendar_plan_instances",
        "schedule",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="schedule::json",
    )
    op.create_index(
        op.f("ix_calendar_plan_instances_id"),
        "calendar_plan_instances",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_plan_instances_user_id"),
        "calendar_plan_instances",
        ["user_id"],
        unique=False,
    )
    op.add_column("calendar_plans", sa.Column("user_id", sa.String(), nullable=True))
    op.alter_column(
        "calendar_plans",
        "schedule",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="schedule::json",
    )
    op.alter_column(
        "calendar_plans",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        op.f("ix_calendar_plans_id"), "calendar_plans", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_plans_user_id"), "calendar_plans", ["user_id"], unique=False
    )
    op.drop_column("calendar_plans", "created_at")
    op.drop_column("calendar_plans", "updated_at")
    op.drop_column("calendar_plans", "is_favorite")
    op.add_column(
        "favorite_calendar_plans", sa.Column("user_id", sa.String(), nullable=True)
    )
    op.execute(
        "UPDATE favorite_calendar_plans SET user_id = 'admin_placeholder' WHERE user_id IS NULL"
    )
    op.alter_column(
        "favorite_calendar_plans", "user_id", existing_type=sa.String(), nullable=False
    )
    op.drop_constraint(
        op.f("favorite_calendar_plans_calendar_plan_id_key"),
        "favorite_calendar_plans",
        type_="unique",
    )
    op.create_index(
        op.f("ix_favorite_calendar_plans_user_id"),
        "favorite_calendar_plans",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_favorite_calendar_plans_user_id"), table_name="favorite_calendar_plans"
    )
    op.create_unique_constraint(
        op.f("favorite_calendar_plans_calendar_plan_id_key"),
        "favorite_calendar_plans",
        ["calendar_plan_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("favorite_calendar_plans", "user_id")
    op.add_column(
        "calendar_plans",
        sa.Column(
            "is_favorite",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "calendar_plans",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "calendar_plans",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_calendar_plans_user_id"), table_name="calendar_plans")
    op.drop_index(op.f("ix_calendar_plans_id"), table_name="calendar_plans")
    op.alter_column(
        "calendar_plans",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "calendar_plans",
        "schedule",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("calendar_plans", "user_id")
    op.drop_index(
        op.f("ix_calendar_plan_instances_user_id"), table_name="calendar_plan_instances"
    )
    op.drop_index(
        op.f("ix_calendar_plan_instances_id"), table_name="calendar_plan_instances"
    )
    op.alter_column(
        "calendar_plan_instances",
        "schedule",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("calendar_plan_instances", "user_id")
    op.drop_index(
        op.f("ix_applied_calendar_plans_user_id"), table_name="applied_calendar_plans"
    )
    op.drop_index(
        op.f("ix_applied_calendar_plans_id"), table_name="applied_calendar_plans"
    )
    op.alter_column(
        "applied_calendar_plans",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_column("applied_calendar_plans", "user_id")
    op.drop_constraint(None, "applied_calendar_plan_user_maxes", type_="foreignkey")
    # ### end Alembic commands ###
