"""plans: update models

Revision ID: 59db877b002f
Revises: 19473c980758
Create Date: 2025-11-23 13:21:25.267005
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59db877b002f"
down_revision = "19473c980758"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
