"""Remove cross-service foreign keys4

Revision ID: 717bb099f1e8
Revises: e65edff077c9
Create Date: 2025-09-19 17:11:50.120461
"""

# revision identifiers, used by Alembic.
revision = "717bb099f1e8"
down_revision = "e65edff077c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
