"""add workout models for plan3

Revision ID: af89147690ca
Revises: df5f21fbee49
Create Date: 2025-09-20 03:49:41.606885
"""

# revision identifiers, used by Alembic.
revision = "af89147690ca"
down_revision = "df5f21fbee49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
