"""add workout models for plan

Revision ID: db821c13a941
Revises: 717bb099f1e8
Create Date: 2025-09-20 01:17:12.322127
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'db821c13a941'
down_revision = '717bb099f1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
