"""add workout models for plan2

Revision ID: df5f21fbee49
Revises: f445c79a9403
Create Date: 2025-09-20 02:29:48.699501
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'df5f21fbee49'
down_revision = 'f445c79a9403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
