"""initial_schema

Revision ID: e4e18296237c
Revises: 
Create Date: 2025-09-17 00:29:52.633298
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4e18296237c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_plans_id'), 'calendar_plans', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_plans_user_id'), 'calendar_plans', ['user_id'], unique=False)
    op.create_table('applied_calendar_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('calendar_plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_max_ids', sa.JSON(), nullable=True),
    sa.Column('current_workout_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_plan_id'], ['calendar_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_calendar_plans_id'), 'applied_calendar_plans', ['id'], unique=False)
    op.create_index(op.f('ix_applied_calendar_plans_user_id'), 'applied_calendar_plans', ['user_id'], unique=False)
    op.create_table('mesocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('weeks_count', sa.Integer(), nullable=True),
    sa.Column('microcycle_length_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_plan_id'], ['calendar_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesocycles_id'), 'mesocycles', ['id'], unique=False)
    op.create_table('applied_plan_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applied_plan_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applied_plan_id'], ['applied_calendar_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_plan_workouts_id'), 'applied_plan_workouts', ['id'], unique=False)
    op.create_table('microcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('normalization_value', sa.Float(), nullable=True),
    sa.Column('normalization_unit', sa.String(length=16), nullable=True),
    sa.Column('days_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcycles_id'), 'microcycles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microcycles_id'), table_name='microcycles')
    op.drop_table('microcycles')
    op.drop_index(op.f('ix_applied_plan_workouts_id'), table_name='applied_plan_workouts')
    op.drop_table('applied_plan_workouts')
    op.drop_index(op.f('ix_mesocycles_id'), table_name='mesocycles')
    op.drop_table('mesocycles')
    op.drop_index(op.f('ix_applied_calendar_plans_user_id'), table_name='applied_calendar_plans')
    op.drop_index(op.f('ix_applied_calendar_plans_id'), table_name='applied_calendar_plans')
    op.drop_table('applied_calendar_plans')
    op.drop_index(op.f('ix_calendar_plans_user_id'), table_name='calendar_plans')
    op.drop_index(op.f('ix_calendar_plans_id'), table_name='calendar_plans')
    op.drop_table('calendar_plans')
    # ### end Alembic commands ###
