"""add microcycle metadata

Revision ID: eafa767832ad
Revises: fix_exercise_columns_mismatch
Create Date: 2025-10-02 20:03:20.038857
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eafa767832ad'
down_revision = 'fix_exercise_columns_mismatch'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_progress', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_progress', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
