"""plans: update models

Revision ID: f990c648024b
Revises: fe12ab34cd56
Create Date: 2025-11-15 22:10:10.162708
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f990c648024b'
down_revision = 'fe12ab34cd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applied_calendar_plans', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('planned_sessions_total', sa.Integer(), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('actual_sessions_completed', sa.Integer(), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('adherence_pct', sa.Float(), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('notes', sa.String(length=512), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('dropout_reason', sa.String(length=64), nullable=True))
    op.add_column('applied_calendar_plans', sa.Column('dropped_at', sa.DateTime(), nullable=True))
    op.add_column('calendar_plans', sa.Column('notes', sa.String(length=512), nullable=True))
    op.add_column('calendar_plans', sa.Column('primary_goal', sa.String(length=32), nullable=True))
    op.add_column('calendar_plans', sa.Column('intended_experience_level', sa.String(length=32), nullable=True))
    op.add_column('calendar_plans', sa.Column('intended_frequency_per_week', sa.Integer(), nullable=True))
    op.add_column('calendar_plans', sa.Column('session_duration_target_min', sa.Integer(), nullable=True))
    op.add_column('calendar_plans', sa.Column('primary_focus_lifts', sa.JSON(), nullable=True))
    op.add_column('calendar_plans', sa.Column('required_equipment', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_plans', 'required_equipment')
    op.drop_column('calendar_plans', 'primary_focus_lifts')
    op.drop_column('calendar_plans', 'session_duration_target_min')
    op.drop_column('calendar_plans', 'intended_frequency_per_week')
    op.drop_column('calendar_plans', 'intended_experience_level')
    op.drop_column('calendar_plans', 'primary_goal')
    op.drop_column('calendar_plans', 'notes')
    op.drop_column('applied_calendar_plans', 'dropped_at')
    op.drop_column('applied_calendar_plans', 'dropout_reason')
    op.drop_column('applied_calendar_plans', 'notes')
    op.drop_column('applied_calendar_plans', 'adherence_pct')
    op.drop_column('applied_calendar_plans', 'actual_sessions_completed')
    op.drop_column('applied_calendar_plans', 'planned_sessions_total')
    op.drop_column('applied_calendar_plans', 'status')
    op.create_table('mesocycle_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mesocycle_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('weeks_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('microcycle_length_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('normalization_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('normalization_unit', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mesocycle_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_mesocycle_templates_user_id'), 'mesocycle_templates', ['user_id'], unique=False)
    op.create_index(op.f('ix_mesocycle_templates_id'), 'mesocycle_templates', ['id'], unique=False)
    op.create_table('microcycle_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mesocycle_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schedule_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_template_id'], ['mesocycle_templates.id'], name=op.f('microcycle_templates_mesocycle_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('microcycle_templates_pkey'))
    )
    op.create_index(op.f('ix_microcycle_templates_mesocycle_template_id'), 'microcycle_templates', ['mesocycle_template_id'], unique=False)
    op.create_index(op.f('ix_microcycle_templates_id'), 'microcycle_templates', ['id'], unique=False)
    # ### end Alembic commands ###
