[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
user=root

[program:http-server]
command=uvicorn exercises_service.main:app --host 0.0.0.0 --port 8002
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/http-server-stderr.log
stdout_logfile=/var/log/supervisor/http-server-stdout.log
environment=PYTHONUNBUFFERED="1"

[program:grpc-server]
command=python -m exercises_service.grpc_server
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/grpc-server-stderr.log
stdout_logfile=/var/log/supervisor/grpc-server-stdout.log
environment=PYTHONUNBUFFERED="1"
