# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x11workoutapp.common\";\n\x0bUserContext\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x8e\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32%.workoutapp.common.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x11PaginationRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"@\n\x12PaginationResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"\x07\n\x05\x45mptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_USERCONTEXT']._serialized_start=35
  _globals['_USERCONTEXT']._serialized_end=94
  _globals['_ERROR']._serialized_start=97
  _globals['_ERROR']._serialized_end=239
  _globals['_ERROR_DETAILSENTRY']._serialized_start=193
  _globals['_ERROR_DETAILSENTRY']._serialized_end=239
  _globals['_PAGINATIONREQUEST']._serialized_start=241
  _globals['_PAGINATIONREQUEST']._serialized_end=289
  _globals['_PAGINATIONRESPONSE']._serialized_start=291
  _globals['_PAGINATIONRESPONSE']._serialized_end=355
  _globals['_EMPTY']._serialized_start=357
  _globals['_EMPTY']._serialized_end=364
# @@protoc_insertion_point(module_scope)
