# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpe.proto\x12\x0eworkoutapp.rpe\x1a\x0c\x63ommon.proto\"\xaf\x02\n\x11RPEComputeRequest\x12\x34\n\x0cuser_context\x18\x01 \x01(\x0b\x32\x1e.workoutapp.common.UserContext\x12\x16\n\tintensity\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x13\n\x06\x65\x66\x66ort\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x13\n\x06volume\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x17\n\nmax_weight\x18\x05 \x01(\x02H\x03\x88\x01\x01\x12\x18\n\x0buser_max_id\x18\x06 \x01(\x05H\x04\x88\x01\x01\x12\x15\n\rrounding_step\x18\x07 \x01(\x02\x12\x15\n\rrounding_mode\x18\x08 \x01(\tB\x0c\n\n_intensityB\t\n\x07_effortB\t\n\x07_volumeB\r\n\x0b_max_weightB\x0e\n\x0c_user_max_id\"\x8b\x01\n\x12RPEComputeResponse\x12\x1c\n\x0f\x63omputed_weight\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x1d\n\x10suggested_weight\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0f\n\x07message\x18\x03 \x01(\tB\x12\n\x10_computed_weightB\x13\n\x11_suggested_weight2^\n\nRPEService\x12P\n\x07\x43ompute\x12!.workoutapp.rpe.RPEComputeRequest\x1a\".workoutapp.rpe.RPEComputeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPECOMPUTEREQUEST']._serialized_start=44
  _globals['_RPECOMPUTEREQUEST']._serialized_end=347
  _globals['_RPECOMPUTERESPONSE']._serialized_start=350
  _globals['_RPECOMPUTERESPONSE']._serialized_end=489
  _globals['_RPESERVICE']._serialized_start=491
  _globals['_RPESERVICE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
