"""crm: stub for lost autogen migration d59950afde1b

Autogenerated migration that existed only inside Docker and was lost when
./alembic was mounted as a volume. We recreate it as a no-op so the
revision graph remains consistent.
"""

import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision = "d59950afde1b"
down_revision = "20251123_add_channel_id"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """No-op placeholder; database is already at this revision."""
    pass


def downgrade() -> None:
    """No-op downgrade; original operations are intentionally omitted."""
    pass
