"""add_app_id_and_context_v2

Revision ID: 57ea359615fc
Revises: 872e178f41b0
Create Date: 2025-11-22 07:15:23.257013

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ea359615fc'
down_revision: str | None = '872e178f41b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('app_id', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('context_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_posts_app_id'), 'posts', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_app_id'), table_name='posts')
    op.drop_column('posts', 'context_resource')
    op.drop_column('posts', 'app_id')
    # ### end Alembic commands ###
