"""exercises: update models"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38c467b9e0b9"
down_revision = "037701b3abb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_exercise_instances_user_id", table_name="exercise_instances")
    op.drop_index("ix_exercise_instances_user_workout", table_name="exercise_instances")
    op.drop_constraint("exercise_instances_exercise_list_id_fkey", "exercise_instances", type_="foreignkey")
    op.create_foreign_key(None, "exercise_instances", "exercise_list", ["exercise_list_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exercise_instances", type_="foreignkey")
    op.create_foreign_key(
        "exercise_instances_exercise_list_id_fkey",
        "exercise_instances",
        "exercise_list",
        ["exercise_list_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_exercise_instances_user_workout", "exercise_instances", ["user_id", "workout_id"], unique=False)
    op.create_index("ix_exercise_instances_user_id", "exercise_instances", ["user_id"], unique=False)
    # ### end Alembic commands ###
