"""remove image_url"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dcae771c7a8'
down_revision = '042135cf4676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index('ix_exercise_instances_id', table_name='exercise_instances')
    op.drop_table('exercise_instances')
    op.drop_index('ix_exercise_list_name', table_name='exercise_list')
    op.create_index(op.f('ix_exercise_list_root_exercise_id'), 'exercise_list', ['root_exercise_id'], unique=False)
    op.drop_column('exercise_list', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_list', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercise_list_root_exercise_id'), table_name='exercise_list')
    op.create_index('ix_exercise_list_name', 'exercise_list', ['name'], unique=True)
    op.create_table('exercise_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_max_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_list_id'], ['exercise_list.id'], name='exercise_instances_exercise_list_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercise_instances_pkey')
    )
    op.create_index('ix_exercise_instances_id', 'exercise_instances', ['id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###
