"""exercises: update models"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dee12d97adb5"
down_revision = "71adca6fe353"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
