"""Manual migration for exercises-service"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'manual_exercises_20250909_202042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by manual migration - adjust for PostgreSQL! ###
    # Example table creation (replace with your actual schema):
    # op.create_table(
    #     'exercises',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('name', sa.String(length=100), nullable=False),
    #     sa.Column('muscle_group', sa.String(length=50), nullable=True),
    #     sa.PrimaryKeyConstraint('id')
    # )
    #
    # Example index creation:
    # op.create_index('idx_exercise_name', 'exercises', ['name'], unique=True)
    #
    # Example enum type creation (PostgreSQL specific):
    # exercise_type = sa.Enum('STRENGTH', 'CARDIO', 'FLEXIBILITY', name='exercise_type')
    # exercise_type.create(op.get_bind())
    #
    # Remember to add all necessary tables, columns, indexes, and constraints
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by manual migration - adjust for PostgreSQL! ###
    # Reverse order of upgrade operations
    #
    # op.drop_index('idx_exercise_name', table_name='exercises')
    # op.drop_table('exercises')
    #
    # Example enum removal:
    # exercise_type = sa.Enum(name='exercise_type')
    # exercise_type.drop(op.get_bind())
    # ### end Alembic commands ###
    pass
